# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2020-08-21 01:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0005_rating_ratingsumary'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='content',
            field=models.TextField(blank=True, default='', verbose_name='\u5185\u5bb9'),
        ),
    ]
