# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2021-08-04 01:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('comment', '0006_rating_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='content_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='contenttypes.ContentType', verbose_name='content type'),
        ),
        migrations.AlterUniqueTogether(
            name='ratingsumary',
            unique_together=set([('content_type', 'object_id')]),
        ),
    ]
